### ISSUE TITLE
Please declare "astroML" and "supersmoother" as dependencies

### ISSUE THREAD

**Issue by anntzer** [astroML/gatspy#13]
... in setup.py, so that `pip install gatspy` "just works".

**Comment by jakevdp** [comment]
I don't generally give pip a list of dependencies in my packages, because I don't generally want pip to do anything unless I explicitly ask it to.

NumPy is also a dependency, for example, but if you list that, then pip will try to install it, which is **never** a good idea. I've had scientific distributions entirely broken (i.e. I had to wipe them clean and start over) because of someone listing dependencies in a small package I wanted to try out.

Thanks for bringing this up, and I hope you can see my perspective!

**Comment by anntzer** [comment]
Would you be willing to reconsider this issue now that manylinux1 wheels are a thing and work decently well?

**Comment by anntzer** [comment]
... especially now that even scipy considers pip good enough to declare a dependency on `numpy` (https://github.com/scipy/scipy/pull/6563, https://github.com/scipy/scipy/pull/6607).
