### ISSUE TITLE
LombScargleFast.find_best_periods does not agree with LombScargleFast.score

### ISSUE THREAD

**Issue by baileyji** [astroML/gatspy#18]
```python
import numpy as np
from astroML.time_series import lomb_scargle_bootstrap
from gatspy.periodic import LombScargleFast

print np.__version__ #1.9.1
print gatspy.__version__ #0.2.1
print astroML.__version__ #0.3

time=np.array([ 2456627.79138722,  2456706.70756269,  2456707.71879721,
                2456710.7089872 ,  2456714.6781531 ,  2457003.78622566,
                2457004.78832308,  2457008.79132022,  2457011.77312267,
                2457013.77502331])
rv=np.array([ 30356.93030223,   6381.7927134 ,   6121.9466685 ,   5884.45430149,
              5641.85369914,  11957.91925097,  12068.74753209,  10966.23226051,
              11870.72687516,   9647.03955393])
e=np.array([ 80.0980572 ,  80.33726674,  80.98308236,  82.29154533,
             91.65632576,  87.24849974,  81.73203085,  82.35611381,
             82.30579078,  79.94037756])

print 'N={}'.format(time.size) #10
print 'T.max()-T.min(): {:.0f}'.format(time.max()-time.min()) #386
print 'stdev(RV): {:.0f}'.format(rv.std()) #6.9 km/s
print 'mean error: {:.0f}'.format(e.mean()) #83 m/s

model = LombScargleFast().fit(time,rv,e)

model.optimizer.period_range=(1.2,3000)
fbpP,fbpS=model.find_best_periods(n_periods=6, return_scores=True)

periods=np.arange(1.2,3000,.1)
scores=model.score(periods)
autoP,autoS=model.periodogram_auto(nyquist_factor=100)

print ('Do scores returned by model.find_best_periods '
       'match those from model.score?')
try:
    assert (model.score(fbpP)==fbpS).all()
    print '   Yes'
except AssertionError:
    print '   No'

print ('Do scores returned by model.periodogram '
       'match those from model.score?')
try:
    assert (model.score(fbpP)==model.periodogram(fbpP)).all()
    print '   Yes'
except AssertionError:
    print '   No'

print ('Do the periods returned by model.find_best_periods have ranking as '
       'those from model.score?')
try:
    assert (model.score(fbpP).argsort()==fbpS.argsort()).all()
    print '   Yes'
except AssertionError:
    print '   No'


D=lomb_scargle_bootstrap(time, rv, e, 1/periods, generalized=True,
                         N_bootstraps=1000, random_state=0)
sig1 = np.percentile(D,[99])
D=lomb_scargle_bootstrap(time, rv, e, 1/autoP, generalized=True,
                         N_bootstraps=1000, random_state=0)
sig1_auto = np.percentile(D,[99])
D=lomb_scargle_bootstrap(time, rv, e, 1/fbpP, generalized=True,
                         N_bootstraps=1000, random_state=0)
sig1_fbpP = np.percentile(D,[99])

plt.plot(autoP,autoS,'k')
plt.axhline(sig1_auto,color='k',linestyle='--')
plt.plot(periods,scores,'r')
plt.axhline(sig1,color='r',linestyle='--')
plt.axhline(sig1_fbpP,color='g',linestyle='--')
plt.ylim(0,2)
plt.xlim(.9,3000)
plt.semilogx()
for i,x,y in zip(fbpS.size-fbpS.argsort(),fbpP, model.score(fbpP)):
    plt.annotate(str(i),(x,y),(x,1.5),
                 arrowprops=dict(facecolor='black', shrink=0.05,
                                 width=.5,headwidth=.5,frac=.1))
plt.axvline(1.2,color='k',linestyle=':')
plt.xlabel('P (days)')
plt.ylabel('LS Power')

handles=[plt.plot([-1,-1],[-1,-2],'k--',label='99% CI')[0],
         plt.plot([-1,-1],[-1,-2],'k',label='Auto P')[0],
         plt.plot([-1,-1],[-1,-2],'k',label='Manual P')[0],
         plt.plot([-1,-1],[-1,-2],'k:',label='Min. physical P')[0]]
plt.legend(loc='upper left',frameon=0)
plt.subplots_adjust(.11,.12,.96,.96)


"""
I would think that at a bare minimum the relative ordering of the periods
from find_best_period would match those from .score and .periodogram.

Thought not demonstrated here, I'm also somewhat unnerved that the scores
returned by.score are a function of the input periods at least at the 3% level.
Which is higher than I'd expect from something like variations due to machine
precision alone.

This, combined with the issue above, makes be uncomfortable quiting 
significance of peaks deriving from both find_best_periods and a manual search
of scores. My initial interest in find_best_periods was that it seemed to offer
an efficient way to account for the frequency gridding seen in peaks located 
using say autoS.argsorted()[::-1][:6] alone. In a large sample of stars this
simplistic approach will see long (~300-2000 day) periods pile up at 
~950,620, 500, etc. days.
""
```

**Comment by jakevdp** [comment]
I'm sorry, I'm not entirely sure what the problem is, because there is a lot of stuff here. Are you primarily concerned that the ``find_best_periods()`` function is not actually finding the best periods, or is it something different than that?

**Comment by jakevdp** [comment]
Also, when you do something like ``periods=np.arange(1.2,3000,.1)``, you are oversampling large periods by far, and undersampling small periods by far. I wouldn't trust any results that come from evaluating lomb scargle power on a uniform period grid like that.

**Comment by baileyji** [comment]
The crux of my confusion is that `model.find_best_periods(n_periods=6, return_scores=True)` does not return what I would call the “best” by looking at the periodogram. The [plot](https://github.com/astroML/gatspy/files/52981/gatspy_plot.pdf) generated by this code shows that find_best_periods is choosing a what I’d consider the 5th best peak (and one that does not cross any of the bootstrapped 99% CI) as the best peak while tagging what I would have thought of as the best peak (and that exceeds the 99% CI) as the 4th best period. 

As to using a fixed period grid, I understand that. I don’t really have a good grasp of what `.optimize` is actually doing, but I got the distinct impression it was looking for an optimal value with a much finer step (for long period peaks, anyway) than the frequency spacing used by `periodogram_auto`. My purpose in oversampling was to see if there was some sort of fine structure in the periodogram at long wavelengths that would explain the values returned by `find_best_peaks`.

**Comment by jakevdp** [comment]
Got it. A couple things:

- I wouldn't expect the assertions to pass, because you're comparing the results of two different algorithms to floating-point precision. ``np.equal()`` will fail while ``np.allclose()`` should pass, if everything else is OK

- You're searching for periods that are longer than the data baseline: the default settings of the optimizer will not work in this regime (The optimizer uses rules-of-thumb for the frequency resolution based on the expectation that the data baseline is longer than the period; I didn't realize that there were any useful situations where this is not the case). You'll have to adjust these settings to get decent results in this case.

All that said, there's still something I'm confused about. For your data, the results of this give scores larger than one:

```
model = LombScargleFast().fit(time, rv, e)
model.optimizer.period_range=(1.2,3000)
fbpP, fbpS=model.find_best_periods(n_periods=6, return_scores=True)
print(fbpP, fbpS)
```

I have no idea how that can happen. I'll do some debugging and try to figure it out.

**Comment by jakevdp** [comment]
In the meantime, I'd suggest not using ``LombScargleFast`` in the regime where you're searching for periods on the order of the data range. The algorithm was not designed for that situation. ``LombScargle`` should work just fine in that case.

I suspect that a documentation change (and perhaps a warning in the code) is the main thing that needs to be done to address this.

**Comment by baileyji** [comment]
You first point makes sense but I'm not sure I fully understand it. I'd expect the periods returned by  `find_best_period` to slightly different from simply picking out the highest N peaks from `periodogram_auto` but I'd naively expect the scores computed by `find_best_period` to match the scores computed by `.score` when applied to the "best" periods from `find_best_period`.

I definitely would have thought the third assertion `model.score(fbpP).argsort()==fbpS.argsort()` would hold, maybe that is because of your second point? I guess I'll need to dive into the code and find those settings. My initial impression was that it isn't heavily documented. 

Regarding longer periods than the baseline: with a baseline of 1 year you've definitely got traction on binaries that are 1-2 years, and can (in my case) at least flag as variable things out to ~50 yr on average. I wouldn't expect any sort of period search to constrain that well, but I would expect them to show periods longer that some value as all being significant. I see that in a number of stars where all periods longer than a certain value are > 95% or 99% significant in stars that are clearly long period binaries.

I didn't think too much about the result being >1 because even `autoS.min()<0` and `autoS.max()>1`.

Reading your second post: I got the impression `LombScargleFast.score` and `LombScargleFast.periodogram` fall back onto the slow implementation. 

Right. I know docs would help me. The innards are clean, but spread over multiple files and use subclasses, which means that it really takes digesting to figure out what is where and how it works.

**Comment by jakevdp** [comment]
> I'd naively expect the scores computed by find_best_period to match the scores computed by .score when applied to the "best" periods from find_best_period.

``LombScargleFast.find_best_period`` uses an FFT-based approximate approach. ``LombScargleFast.score`` uses a direct, non-FFT-based approach (as is indicated by the warning spit out any time you call this method). That's why the results are different.

>  I definitely would have thought the third assertion model.score(fbpP).argsort()==fbpS.argsort() would hold

Yep – this is a result of the ``LombScargleFast`` algorithm giving the wrong result when the period is comparable to the data range. I believe the algorithm simply does not work in that case, and I never thought there would be a situation when it would be used in that way. Like I mentioned, you should use ``LombScargle`` instead, and I should probably put a check in the code to raise a valueerror if someone tries to use input like yours.

> Regarding longer periods than the baseline:

If you want to find periods longer than your baseline, I think LombScargle is fundamentally the wrong algorithm to use. Frankly, I would not expect the algorithm to ever to give useful results in this situation. I'll probably end up adding a ``ValueError`` in the score function to prevent people from making this mistake :smile:

**Comment by baileyji** [comment]
I hear you on all these points. Ultimately I'd guess things periods longer that 2x the baseline all that would get past a referee is P>=x. I think I mentioned the work Prabhu did with Jian Ge a while back and I'm hoping it will have a lot of value since N is so small for me. Right now it is a case of needing a rough estimate for deadlines.

Anyway, I switched to `LombScargle` and now I'm finding that `.find_best_period` occasionally returns values far above `.optimizer.period_range`. For example with the below times, rvs, and errors and having switched over to `LombScargle` I get best periods that generally agree with the peaks except for the last one. The optimizer seems to run away and returns ~200,000 days for data with a baseline of 384 days. I'm not arguing these data have a well constrained period, but 200k is nonsense. Should it be clipped to the shortest frequency and a warning issued?

```python
time=np.array([ 2456618.8046589 ,  2456620.80841927,  2456623.79827557,
                2456624.79765211,  2456626.80094473,  2456704.73283734,
                2456705.69662068,  2456709.71282529,  2457000.78833536,
                2457001.79547542,  2457002.68310949,  2457003.68596521]),
rv=np.array([-44717.57046632, -44680.85170403, -43840.42297019, -43343.31523893,
             -42347.54162634, -25983.85569657, -26035.06263051, -25943.39063373,
             -24387.79567889, -24508.48643314, -24505.53536921, -24470.44141606]),
e=np.array([  92.26731268,  100.98112097,   92.44640623,   98.6191365 ,
              90.01839135,   85.00237548,   75.90438491,   76.63686879,
              83.59888614,  106.82015221,   82.4124667 ,   78.82983289])
```

**Comment by jakevdp** [comment]
Ah – yeah, that's an issue. The problem is the two-stage optimization that the algorithm does. Again, it's designed to work with periods that are small in relation to the data range. If you specify a period larger than the data range, then the second-stage of the fit can choose a grid that goes beyond the original range.

The solution would be to either special-case this situation of asking for very large periods, or simply raise a ValueError because the algorithm as designed will not likely arrive at the right answer anyway.

Again, the period finder code as written will almost never give reasonable results for periods longer than the baseline, and even if I re-wrote the code to do things correctly in this regime, LombScargle will still give answers that are essentially worthless when it comes to answering the question you are asking.

If you want to find periods that are longer than your baseline, you'll need a much more informative model for your data than LombScargle provides.

**Comment by jakevdp** [comment]
See https://github.com/astroML/gatspy/commit/7f1c60ebc8a5f38af9db38bcac13209b412f563a – the code will now raise a ValueError if you try doing what you're doing here.

**Comment by jakevdp** [comment]
Also see this issue: https://github.com/astroML/gatspy/issues/19

I'll try to fix that corner case.

**Comment by jakevdp** [comment]
Thanks for the report here!

**Comment by jakevdp** [comment]
Re-reading this, I think I came across as too dismissive.

There are situations in which searching for periods longer than your data range is useful, and that's when you *know* that your data are near-sinusoidal. In that case, the main issue with ``gatspy`` as currently implemented is that the optimizer is not designed for this situation, where the uncertainty in period estimation is driven by lack of period coverage rather than noise in the data.

To make this work, I think the best path would be to add another optimizer class that works for this situation: i.e. chooses the period/frequency grid based on data-driven estimates of the probable peak width for large periods.

If you'd like to discuss this further, please let me know!

**Comment by jakevdp** [comment]
I've looked into this some more: the key is that the fft-based algorithm in LombScargleFast is an approximation designed for use with large datasets: when you feed it just ten points, the approximation can break (it's very similar to an interpolation: if you sample ten points from a sine wave and then interpolate, you're not likely to approximate the sine wave very well).

In practice, this isn't much of an issue because the fast algorithm only really becomes necessary when your datasets grow large.

To address all of this, I've updated the documentation and added a warning in the case that ``LombScargleFast`` is used on fewer than 50 points: https://github.com/astroML/gatspy/commit/0aeb086640e965516d8ca27bc2075482cb1e4c7b.
Hopefully that will help future users to use the code as it was intended!

Thanks for the report.
