### ISSUE TITLE
optimizer.py: LinearScanOptimzer.find_best_periods is sensitive to time scale

### ISSUE THREAD

**Issue by stharrold** [astroML/gatspy#3]
I found a minor issue with the number of steps required to compute the best period. It seems that the number of steps scales linearly with the scale of the time units. A simple workaround is to just use the MJD time units to prevent the excess calculations.

Example from IPython notebook (below):
* With the units of time values in MJD, max(times) - min(times) may be ~3e3 units (days) and require ~70e3 steps to compute the best period.
* With the units of time values in Unix time, max(times) - min(times) may be ~300e6 units (seconds) and require ~7e9 steps to compute the best period. (In the example ipynb, this example overflows 8GB of RAM.)

Example IPython notebook (taken from [gatspy/examples](https://github.com/astroML/gatspy/tree/master/examples), tests added to end): http://nbviewer.ipython.org/gist/stharrold/874c9f588c02b661b50b

Relevant `gatspy` code: https://github.com/astroML/gatspy/blob/master/gatspy/periodic/optimizer.py#L49-L63

**Comment by stharrold** [comment]
Thanks so much for sharing the awesome package!

**Comment by jakevdp** [comment]
Thanks for checking on this!

I think this is what's going on: the number of steps depends both on the data range and the period range that you're interested in exploring. So if  ``period_range`` and ``times`` have consistent units, then the number of steps will not change as you change the units of the input. Let me know if there's anything I should do to make that more clear in the documentation.

**Comment by stharrold** [comment]
Thanks Jake! That helped. Here's the example ipynb with `gatspy.periodic.optimizer.LinearScanOptimizer` initialized with custom `period_range` and `first_pass_coverage`:
http://nbviewer.ipython.org/gist/stharrold/1f77d1cffa4d1eb7f8d8
In the example ipynb, I included the Nyquist limits since they're often expected as a conservative sanity check, even though they don't apply for irregularly sampled data. My initialization of `LinearScanOptimizer` scans a large range of frequencies inefficiently and takes ~35 minutes.
Thanks again for your help!

**Comment by jakevdp** [comment]
Thanks! I'd encourage you not to even consider Nyquist limits as a sanity check. They're entirely meaningless for irregular data, and pretending otherwise can only mislead you. For example, it's quite easy to find RR Lyrae stars with periods of ~0.6 days within SDSS2 data which has an observing cadence of 2-3 days!

Overzealous application of Nyquist-type limits to irregular data is one of my technical pet peeves, and I've been meaning to write a short blog post or paper on the topic... perhaps this summer.

**Comment by jakevdp** [comment]
Also, you probably don't need a custom ``first_pass_coverage``. The peak width depends on the range of times observed, and first pass coverage is just about choosing more than one point across each peak, so that you don't miss any. Something like ~5 is sufficient regardless of the data themselves.

The main issue is choosing the right period range, and the smaller the lower limit is, the larger frequency grid you'll need to make sure not to miss any peaks.

I'm realizing that I could do a better job of documenting all this...

I've opened an issue (#4) to hopefully remind me of this when I have time to address it...

**Comment by jakevdp** [comment]
Another thing (sorry, I'm looking more closely at your code now): it's better to consider frequency space griddings than period-space griddings. The widths of periodogram peaks are roughly uniform in frequency, and therefore vary in period.

**Comment by jakevdp** [comment]
Also, a lot of the logic in your notebook is already in the ``LinearScanOptimizer``. If you simply pass in the highest and lowest period you're interested in, it will calculate an optimal grid for you.

I think that's it now... :grinning:

**Comment by jakevdp** [comment]
Last thing, I promise: a cleaner way to adjust the grid search is something like this:

``` python
model = LombScargleMultiband()
model.optimizer.period_range = (min_period, max_period)
```

**Comment by stharrold** [comment]
Thanks Jake for the fast, detailed response! I really appreciate your time!

re: non-applicable Nyquist limits
I think a blog post about detecting RR Lyrae stars with periods significantly shorter than the typical observing tempo would be really influential! I guess that shuffling the flux values would be an appropriate way of establishing significance thresholds as a function of period. I'd love to see a robust way of comprehensively searching period space for significant periods. Maybe there's a theorem somewhere in a signal processing textbook. I should do more reading.

re: [#4](https://github.com/astroML/gatspy/issues/4)
Thanks!

re: optimizations and readability improvements
Whoops, good example of how object-oriented programming is a lot more readable than functional programming. Thanks for the code review! I just learned something :)

**Comment by jakevdp** [comment]
Basically it comes down to the convolution theorem. Your observed data is the product of your survey window, which looks like a bunch of delta functions, and the true (smooth) underlying signal. When you Fourier transform this, the result is a convolution of the FT of the window and the FT of the signal. If your observations are equally spaced, the window FT is also a bunch of equally spaced delta functions, and the distance between these delta functions is what leads to the nyquist limit. When your observations are not equally spaced, things don't cancel and you end up with a bunch of sinc functions added together. Just as Nyquist-style aliasing can mess you up for regularly-spaced data, the smeared-out "aliases" due to the irregular window function can mess you up for irregular data. There's no generally-applicable rule-of-thumb because the window FT is so different in every case.

We cover this briefly in section 10.2 of our book, but I think that I could present it in a more compelling way if I put my mind to it...

**Comment by stharrold** [comment]
Thanks as always!
